import os

SUPABASE_URL = os.getenv("SUPABASE_URL")
SUPABASE_SERVICE_ROLE_KEY = os.getenv("SUPABASE_SERVICE_ROLE_KEY")

DEFAULT_TIMEZONE = os.getenv("DEFAULT_TIMEZONE", "Europe/Amsterdam")

FORECAST_HORIZON_QUARTERS = int(os.getenv("FORECAST_HORIZON_QUARTERS", "96"))
LSTM_SEQUENCE_LENGTH = int(os.getenv("LSTM_SEQUENCE_LENGTH", "192"))
PV_LOOKBACK_DAYS = int(os.getenv("PV_LOOKBACK_DAYS", "180"))
LOAD_LOOKBACK_DAYS = int(os.getenv("LOAD_LOOKBACK_DAYS", "365"))
